substitutions:
  _IMAGE: 'gcr.io/whiteblock/geth'
  _DIR: 'ethereum/geth'
timeout: '20m'
steps:
# build final docker image
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE:$BRANCH_NAME',
            '-t', '$_IMAGE:$COMMIT_SHA',
            '.'
        ]
  dir: '$_DIR'
  waitFor: ['-']
# push docker image tag(s) one branch, one immutable
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$COMMIT_SHA' ]
  waitFor:
    - 'build'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$BRANCH_NAME' ]
  waitFor:
    - 'build'

options:
  machineType: 'N1_HIGHCPU_8'
images: ['$_IMAGE:$BRANCH_NAME', '$_IMAGE:$COMMIT_SHA']
